---

# Copyright (c) 2020 Ilya Fralkou
#
# Unlicense
#
#     https://unlicense.org
#

- name: apt-get update
  apt:
    update_cache: true
  changed_when: false
  tags: bootstrap

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt + linux_base_packages_extra }}"
  register: result
  until: result is succeeded
  tags: bootstrap

- name: uninstall packages unnecessary for a minimal base
  apt:
    name: '{{ item }}'
    state: absent
    purge: yes
    autoremove: yes
  with_items: '{{ linux_base_uninstall_packages }}'
  tags: bootstrap
